### ISSUE TITLE
ImportError: No module named 'preprocessing'

### ISSUE THREAD

**Issue by NLaloum** [AxeldeRomblay/MLBox#1]
Hi team, 

This might just be an issue with the __init__ files, 

but I get this when importing mlbox.preprocessing

```
      6 
      7 
----> 8 from preprocessing import *
      9 from encoding import *
     10 from optimisation import *

ImportError: No module named 'preprocessing'
```

Thanks for helping !

**Comment by AxeldeRomblay** [comment]
Yes, I am working on this actually and I'll fix that soon... This a compatibility issue when using python 3.

**Comment by NeerajSarwan** [comment]
Is this issue resolved? Because I still get the error No module named 'preprocessing' while trying to import mlbox.

**Comment by AxeldeRomblay** [comment]
No unfortunately mlbox does not support Python 3 at the moment...
