### ISSUE TITLE
DL methods in MLBox

### ISSUE THREAD

**Issue by GaganaB** [AxeldeRomblay/MLBox#100]
Hi. I was wondering if there's a way to try deep learning methods on CSV files in MLBox? Thank you.

**Comment by AxeldeRomblay** [comment]
Hello @GaganaB, what do you mean by trying DL models on csv files ? Actually you can read csv files with MLBox and encode categorical features using DL methods... : https://mlbox.readthedocs.io/en/latest/features.html#categorical-features
Hope it helps.
