### ISSUE TITLE
How to specify categorical columns

### ISSUE THREAD

**Issue by MasterXiong** [AxeldeRomblay/MLBox#102]
Hi, thanks for providing such a useful toolkit. I want to ask that when we use Optimizer.optimise(space, data), how should we setup the input data so that mlbox could know which columns are categorical features that need to apply the encoding strategy? Thanks.

**Comment by AxeldeRomblay** [comment]
Hello @MasterXiong ! You don't need to specify which columns are categorical features (neither dates or lists or whatever...), MLBox will detect automatically :)
