### ISSUE TITLE
How to check confusion matrix?

### ISSUE THREAD

**Issue by nithinreddyy** [AxeldeRomblay/MLBox#110]
Hey, how to check confusion matrix and how extract true positives data? I mean if we have 92% of true positives, then how to extract that data?

**Comment by AxeldeRomblay** [comment]
Hello @nithinreddyy, at the moment this feature is not in MLBox. But could be interesting to add it !

**Comment by nithinreddyy** [comment]
> Hello @nithinreddyy, at the moment this feature is not in MLBox. But could be interesting to add it !

Yea please do that. Thanks
