### ISSUE TITLE
How to add algorithms on our choice in this?

### ISSUE THREAD

**Issue by nithinreddyy** [AxeldeRomblay/MLBox#111]
like normally RandomForest, LightGBM is present in code. Can we add decision trees, logistic regression and Knn etc?

**Comment by AxeldeRomblay** [comment]
Hello @nithinreddyy, as written in the doc trees & logistic regression are already in the MLBox...

**Comment by nithinreddyy** [comment]
> Hello @nithinreddyy, as written in the doc trees & logistic regression are already in the MLBox...

Great, Thanks
