### ISSUE TITLE
params of classifiers

### ISSUE THREAD

**Issue by KleinXin** [AxeldeRomblay/MLBox#115]
It seems the params of classifiers are set as default in optimiser.py

Only LightGBM is used by default.

Is there any way to set params so that different classifiers can be used in stead of LightGBM?

The only way is to change the source codes if I want to use RandomForest？

**Comment by AxeldeRomblay** [comment]
Hello @KleinXin, 
You can have a look here : https://mlbox.readthedocs.io/en/latest/features.html#mlbox.model.classification.Classifier 
Thanks !
