### ISSUE TITLE
You have no test dataset

### ISSUE THREAD

**Issue by slgero** [AxeldeRomblay/MLBox#120]
Hello, I try to follow steps as shown in [this example](https://github.com/AxeldeRomblay/MLBox/blob/master/examples/classification/example.ipynb), but I get an error `You have no test dataset`. How can I solve this problem?

![image](https://user-images.githubusercontent.com/47792593/101639618-91996800-3a40-11eb-9599-78db780494fe.png)

**Comment by ThomasBourgeois** [comment]
I had this the other day. It's explained in the doc, you have to put at least one path where you input a test set, that is, one where the target is not present.

**Comment by slgero** [comment]
@ThomasBourgeois Thank you very much!
