### ISSUE TITLE
 IOError: You have attempted to connect to an IPython Cluster but no Controller could be found

### ISSUE THREAD

**Issue by paduel** [AxeldeRomblay/MLBox#16]
Hi. I tried the 'Getting started: 30 seconds to MLBox', but I have this error when read and preprocess the files:

```
data = Reader(sep=",").train_test_split(paths, target_name)  #reading
data = Drift_thresholder().fit_transform(data)  #deleting non-stable variables
```
```
IOError: You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.
```

Before  successfully  started a cluster with:

```ipcluster start```

Also I checked at the same notebook this without error:

```
import os
import ipyparallel as ipp
rc = ipp.Client()
ar = rc[:].apply_async(os.getpid)
pid_map = ar.get_dict()
pid_map
```
```
{0: 10634,
 1: 10639,
 2: 10644,
 3: 10649,
 4: 10654,
 5: 10674,
 6: 10662,
 7: 10688}
```
Could you help me?  I really want to try your MLBox  :smile: 

Thanks.

**Comment by paduel** [comment]
I tried to copy the directory ~/.ipython/profile_default to ~/.jupyter/profile_default  and didn't work.

**Comment by AxeldeRomblay** [comment]
Hello, 

hum did you wait 30 sec after importing mlbox ? Otherwise, It won't work and you will have to stop ipcluster engines : 

`os.system("ipcluster stop --profile=home &")`

and start a again : 

`os.system("ipcluster start --profile=home &")`

**Comment by gvyshnya** [comment]
I see the same issue on my end too. Here is the stack trace of the error on my end:

`Traceback (most recent call last):
  File "E:/some_folder/mlbox_pipeline.py", line 19, in <module>
    data=mlb.preprocessing.Reader(sep=",").train_test_split(["data/train_imputed2.csv","data/test_imputed2.csv"],'SalePrice')
  File "C:\ProgramData\Anaconda3\lib\site-packages\mlbox\preprocessing\reader.py", line 175, in __init__
    self.__client = ipp.Client(profile='home')
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipyparallel\client\client.py", line 399, in __init__
    raise IOError(no_file_msg)
OSError: You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.`

P.S. I managed to install MLBox on Windows 7, 64-bit

**Comment by AxeldeRomblay** [comment]
It has just been fixed, so you can have a try ! It should work now..
