### ISSUE TITLE
pip install looks OK, but import mlbox fails

### ISSUE THREAD

**Issue by ghost** [AxeldeRomblay/MLBox#19]
Hi Axel,

I tried to install MLBox on my Ubuntu 16.04 system. 

I created a virtual environment with anaconda, then activate the environment and proceed to installation 
> conda create -n py35mlbox python=3.5 anaconda
> source activate py35mlbox
> sudo apt-get install build-essential
> pip install cmake
> pip install mlbox

All this did run OK. After that, I tried to run a python script with the instruction "from mlbox.optimisation import *" in it. The following error message was returned : "ImportError: No module named 'mlbox'."
Then I created an ipython kernel like this :
> python -m ipykernel install --user --name py35mlbox --display-name "py35mlbox"

In the ipython console I tried to import mlbox:

In [2]: import mlbox
/home/drussier/anaconda2/envs/py35mlbox/lib/python3.5/site-packages/mlbox/preprocessing/drift/__init__.py:9: UserWarning: ipCluster is starting. Please wait 30 sec and check in terminal that 'the engines appear to have started successfully'.
  warnings.warn("ipCluster is starting. Please wait 30 sec and check in terminal that 'the engines appear to have started successfully'.")
Using Theano backend.
Traceback (most recent call last):
  File "/usr/bin/ipcluster", line 4, in <module>
    from IPython.parallel.apps.ipclusterapp import launch_new_instance
  File "/usr/lib/python2.7/dist-packages/IPython/parallel/__init__.py", line 21, in <module>
    import zmq
ImportError: No module named zmq
  File "/home/drussier/anaconda2/envs/py35mlbox/lib/python3.5/site-packages/mlbox/optimisation/optimiser.py", line 69
    self.to_path = to_path
                          ^
TabError: inconsistent use of tabs and spaces in indentation

In [3]: Traceback (most recent call last):
  File "/usr/bin/ipcluster", line 4, in <module>
    from IPython.parallel.apps.ipclusterapp import launch_new_instance
  File "/usr/lib/python2.7/dist-packages/IPython/parallel/__init__.py", line 21, in <module>
    import zmq
ImportError: No module named zmq

Then nothing happens. It looks like there is a wrong path setting : "/usr/lib/python2.7/dist-packages/IPython/parallel/__init__.py" is not a file from my virtual environnment.

Do you have an idea what's going on ?

Thanks

**Comment by AxeldeRomblay** [comment]
Hello,
Can you download and install mlbox from the github please ? 
I have fixed an error...
Thks

**Comment by Henri-Gerard** [comment]
I am closing this issue as there are no more messages since July 2017
