### ISSUE TITLE
Testing with Predicting Blood Donation challenge

### ISSUE THREAD

**Issue by brunosez** [AxeldeRomblay/MLBox#2]
Hi,
Doing some tests with this challenge
https://www.drivendata.org/competitions/2/warm-up-predict-blood-donations/

With minimal understanding I rank around 700 on 2400 !
I must document some questions on 
how to get features importance
how to set up stacking

Rgds
Bruno Seznec

**Comment by AxeldeRomblay** [comment]
Hello Bruno, 

Good to see it works ;) I am working on the doc at the moment so don't worry, it will be soon available. 
- Feature importance is saved in the folder "save" 
- here is a code to stack several models (you can adapt it) : 

params = {
   
    "stck1__base_estimators" : [ 
        Classifier(strategy = "XGBoost", n_estimators=800, max_depth= 4,subsample = 0.8), 
        Classifier(strategy = "LightGBM",n_estimators=800, learning_rate=0.02, max_depth= 4),  
        Classifier(strategy = "RandomForest",n_estimators=800, max_depth=12, max_features = 0.77), 
        Classifier(strategy = "ExtraTrees",n_estimators=800,max_depth=11, max_features = 0.85), 
        Classifier(strategy = "Linear", penalty="l2", C = 1.8,random_state=29), 
    ],   
     "stck1__n_folds" : 6, 
             
     'est__strategy' : "XGBoost", 'est__n_estimators' : 200, 'est__learning_rate': 0.05, 'est__max_depth': 3
}

Then: 

prd = Predictor()
prd.fit_predict(params ,df)

Let me know if it's ok... 
Axel

**Comment by AxeldeRomblay** [comment]
Here is the doc: https://github.com/AxeldeRomblay/MLBox/blob/master/docs/documentation.md

**Comment by brunosez** [comment]
Hi Axel

In fact with the stacking, I got
Traceback (most recent call last):
  File "mlbox1.py", line 74, in <module>
    prd.fit_predict(params,df)
  File "/home/consult/anaconda/lib/python2.7/site-packages/mlbox-0.2.2-py2.7.egg/mlbox/prediction/predictor.py", line 339, in fit_predict
    raise ValueError("Can not predict")
ValueError: Can not predict
[mlbox1.py.txt](https://github.com/AxeldeRomblay/MLBox/files/1086500/mlbox1.py.txt)

**Comment by AxeldeRomblay** [comment]
Ok so I've just fixed it and tested on your challenge and now it works... You can re-download/clone the master (or dev) branch.
Thank you for reporting me this error and enjoy your competition !

**Comment by brunosez** [comment]
Hi Axel,
Thanks it is corrected, with stacking , my rank increased around 100 !
You can close the issue.
It is not clear how to get feature importance ?
Note : I will present some pointers to your framework at the Kaggle Paris Meetup
the 4th of july, are you available at this date

**Comment by AxeldeRomblay** [comment]
Great :) 
- Feature importance is the sklearn feature importance or coeff for a linear model... You do no need to code to get it, just call fit_predict method and look at "save" folder.
- Yes I will be available ! You can contact me via email/linkedin

**Comment by brunosez** [comment]
Ok, it will be announced in the next day, location Equancy near the Trocadero.
Thanks to participate.
Bruno
