### ISSUE TITLE
FYI: ColumnTransformer

### ISSUE THREAD

**Issue by amueller** [AxeldeRomblay/MLBox#26]
We'll have a ColumnTransformer in sklearn pretty soon that will make it easier to treat different columns differently. That should make is much simpler to have different pipelines for categorical and continuous data, which seems one of the big issues MLBox addresses.

**Comment by AxeldeRomblay** [comment]
Great news !! :) When is the release ?

**Comment by amueller** [comment]
It's not merged yet, so it won't be in the upcoming 0.19 release. So winter?

**Comment by AxeldeRomblay** [comment]
Ok I will see how we can integrate this new feature into MLBox without making it too complicated to tune..

**Comment by AxeldeRomblay** [comment]
Hello @amueller ! 
I am working on some encoders (IndexEncoder, CategoricalEncoder, TextEncoder...) for the next release of MLBox and so I will now be interested in ColumnTransformer :) 
When do you think it will be released ? 
Thanks

**Comment by amueller** [comment]
It has not been merged yet. I hope it will get merged this year (fingers crossed). It will be in the 0.20 release which might be in spring?

**Comment by AxeldeRomblay** [comment]
Great ! Looking forward to try it !

**Comment by brunosez** [comment]
Available in 0.20 :-)

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since this feature will be added to a next release (MLBox 1.0.0 probably)
