### ISSUE TITLE
dict target

### ISSUE THREAD

**Issue by ilyes495** [AxeldeRomblay/MLBox#34]
I have a question regarding the format of target dataframe which is passed to fit_predict(), does it contain the labels of training dataset or for test dataset as well ? and how it should be formatted?
I think it's not clear if someone has to process the data himself before passing it to the predictor.

Thanks

**Comment by AxeldeRomblay** [comment]
The "target dataframe" (actually it must be a **pandas Serie**) must contain the labels of training dataset only. 

- The indexes of the target should also match with the train dataset. 
- The serie's name must correspond to your target name
- dtype = 'int' for classif (as you're supposed to have encoded it before) or dtype = 'float' for regression

Also if you're dealing with a classification problem, **you need to have the target encoder python object in the directory "save" (`LabelEncoder`fitted)** and saved as "target_encoder.obj"

**Comment by AxeldeRomblay** [comment]
I will add more details to the docs tomorrow ! Thanks for reporting this issue !
