### ISSUE TITLE
NameError for DriftEstimator

### ISSUE THREAD

**Issue by wrangel** [AxeldeRomblay/MLBox#36]
When computing drifts (Jupyter Notebook, MLBox 0.4.4) using the notebook in [the classification example](https://github.com/AxeldeRomblay/MLBox/tree/master/examples/classification) 

`dft = Drift_thresholder()` 
`df = dft.fit_transform(df)`

I get a name error:

> computing drifts...
[0:apply]: 
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<string> in <module>()
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\ipyparallel\client\remotefunction.py in <lambda>(f, *sequences)
    248             if _mapping:
    249                 if sys.version_info[0] >= 3:
--> 250                     f = lambda f, *sequences: list(map(f, *sequences))
    251                 else:
    252                     f = map
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\mlbox\preprocessing\drift\drift_threshold.py in sync_fit(df_train, df_test, estimator, n_folds, stratify, random_state)
     46 
     47     # We will compute the indices of the CV in each thread
---> 48     de = DriftEstimator(estimator, n_folds, stratify, random_state)
     49     de.fit(df_train, df_test)
     50 
NameError: name 'DriftEstimator' is not defined

>[1:apply]: 
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<string> in <module>()
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\ipyparallel\client\remotefunction.py in <lambda>(f, *sequences)
    248             if _mapping:
    249                 if sys.version_info[0] >= 3:
--> 250                     f = lambda f, *sequences: list(map(f, *sequences))
    251                 else:
    252                     f = map
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\mlbox\preprocessing\drift\drift_threshold.py in sync_fit(df_train, df_test, estimator, n_folds, stratify, random_state)
     46 
     47     # We will compute the indices of the CV in each thread
---> 48     de = DriftEstimator(estimator, n_folds, stratify, random_state)
     49     de.fit(df_train, df_test)
     50 
NameError: name 'DriftEstimator' is not defined

>[2:apply]: 
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<string> in <module>()
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\ipyparallel\client\remotefunction.py in <lambda>(f, *sequences)
    248             if _mapping:
    249                 if sys.version_info[0] >= 3:
--> 250                     f = lambda f, *sequences: list(map(f, *sequences))
    251                 else:
    252                     f = map
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\mlbox\preprocessing\drift\drift_threshold.py in sync_fit(df_train, df_test, estimator, n_folds, stratify, random_state)
     46 
     47     # We will compute the indices of the CV in each thread
---> 48     de = DriftEstimator(estimator, n_folds, stratify, random_state)
     49     de.fit(df_train, df_test)
     50 
NameError: name 'DriftEstimator' is not defined

>[3:apply]: 
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<string> in <module>()
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\ipyparallel\client\remotefunction.py in <lambda>(f, *sequences)
    248             if _mapping:
    249                 if sys.version_info[0] >= 3:
--> 250                     f = lambda f, *sequences: list(map(f, *sequences))
    251                 else:
    252                     f = map
c:\users\wettsteinm\appdata\local\continuum\anaconda3\lib\site-packages\mlbox\preprocessing\drift\drift_threshold.py in sync_fit(df_train, df_test, estimator, n_folds, stratify, random_state)
     46 
     47     # We will compute the indices of the CV in each thread
---> 48     de = DriftEstimator(estimator, n_folds, stratify, random_state)
     49     de.fit(df_train, df_test)
     50 
NameError: name 'DriftEstimator' is not defined

**Comment by AxeldeRomblay** [comment]
Thanks for reporting this issue ! I will fix that asap and keep you in touch.

**Comment by AxeldeRomblay** [comment]
It has just been fixed, so you can have a try ! It should work now..

**Comment by wrangel** [comment]
Working indeed. Thanks.
