### ISSUE TITLE
maplotlib import error

### ISSUE THREAD

**Issue by NCherel** [AxeldeRomblay/MLBox#4]
matplotlib is missing from requirements.txt leading to an error when importing mlbox.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mlbox/__init__.py", line 11, in <module>
    from prediction import *
  File "mlbox/prediction/__init__.py", line 1, in <module>
    from predictor import *
  File "mlbox/prediction/predictor.py", line 14, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
```

**Comment by AxeldeRomblay** [comment]
do you use anaconda distribution ?

**Comment by NCherel** [comment]
No, just Python 2.7 and pip

**Comment by AxeldeRomblay** [comment]
ok perfect ! That's why I just realize that matplotlib was missing... Now it is fixed ! Also do you have the following packages : 
- os
- warnings
- copy
- time
- operator
- pickle
- sys

**Comment by NCherel** [comment]
Yes I have all of them in a brand new virtual env

**Comment by AxeldeRomblay** [comment]
ok so need to add them in the requirements ...
