### ISSUE TITLE
Installed mlbox but stuck at importing

### ISSUE THREAD

**Issue by sugiantolauw** [AxeldeRomblay/MLBox#41]
Hi Team,

I was excited in trying out mlbox but its stuck at importing.

So I have managed to installed the package, but its just stuck at importing.

This line: from mlbox.preprocessing import *

I wasnt able to get the background process error because it didnt come up in my command line.

I was wondering if you guys aware of this?

Best,

Sugi

**Comment by AxeldeRomblay** [comment]
Hello Sugi,
Can you please tell me the OS and the IDE you're using ? At the moment MLBox runs on Ubuntu and works better on Jupyter notebook...

**Comment by sugiantolauw** [comment]
Hi Axel,

Absolutely. I am on Windows 10 and i am using Jupyter notebook.

Looks like from what you are saying, it might be because I am using windows 10....

**Comment by AxeldeRomblay** [comment]
Yes pretty sure...
