### ISSUE TITLE
pipeline cannot be fitted

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [AxeldeRomblay/MLBox#43]
Hello,

I got this error message when i ran my model, what does this actually mean?

`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ BEST HYPER-PARAMETERS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

{'fs__threshold': 0.23151363142104533, 'ce__strategy': 'label_encoding', 'est__max_depth': 7, 'ne__categorical_strategy': nan, 'est__n_estimators': 500, 'fs__strategy': 'l1', 'ne__numerical_strategy': 'mean'}

fitting the pipeline ...
Traceback (most recent call last):
  File "mlbox_model.py", line 66, in <module>
    sys.exit(main())
  File "mlbox_model.py", line 62, in main
    mlboxfunc()
  File "mlbox_model.py", line 39, in mlboxfunc
    Predictor().fit_predict(best,df)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mlbox/prediction/predictor.py", line 389, in fit_predict
    raise ValueError("Pipeline cannot be fitted")
ValueError: Pipeline cannot be fitted
`

**Comment by AxeldeRomblay** [comment]
Hello, 
`'ne__categorical_strategy': nan` is deprecated in version 0.5. You can try the following choices instead : 
- `'ne__categorical_strategy': '<NULL>'`
- `'ne__categorical_strategy': 'most_frequent'`
Please tell me if it works then...

**Comment by Jeeva-Ganesan** [comment]
Thanks it worked. :) Closing it.
