### ISSUE TITLE
Feature Request: Leave one out encoding 

### ISSUE THREAD

**Issue by jithurjacob** [AxeldeRomblay/MLBox#53]
Hi,

 I have seen Owen Zhang( Kaggle #1) [explaining](https://youtu.be/LgLcfZjNF44)  how Leave one out encoding is useful for categorical encoding. Could you please review the usefulness of this technique and add it to the library?

[code sample](https://stackoverflow.com/questions/39129085/pandas-realization-of-leave-one-out-encoding-for-categorical-features)

**Comment by AxeldeRomblay** [comment]
Hello ! 
Nice idea :) I will try do it at the end of the year... also encoding text features would be very useful !

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since this feature will be added in a next release (MLBox 1.0.0 probably)
