### ISSUE TITLE
Overriding string numerical conversion

### ISSUE THREAD

**Issue by jithurjacob** [AxeldeRomblay/MLBox#54]
Hi,

For a data set I'm using the target and categorical variables are already label encoded to integers. MLBox is incorrectly identifying the categorical values & target as continuous. Thus MLBox is incorrectly converting a classification task into a regression task. 

I tried setting the columns as string but still MLBox is converting to integer. Can I override this behavior?

[dataset](https://www.hackerearth.com/challenge/competitive/machine-learning-challenge-4/)

**Comment by AxeldeRomblay** [comment]
Hello ! 

You're right : MLBox tries to cast "fake" categorical features with levels like "1", ... For the next release, the target won't be casted but the features will still be. To avoid this, unfortunately, you will need to append to each level a string like "level" : 
`.apply(lambda x: "level"+str(x))` 

Hope it will help you !

**Comment by jithurjacob** [comment]
Thanks that helps
