### ISSUE TITLE
Install fails. Can't tell if it is MLbox or XGboost that doesnt work

### ISSUE THREAD

**Issue by brcacrm** [AxeldeRomblay/MLBox#55]
Hi Axel,

We're trying to install MLbox and get the following error : 
```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ob6fq6jv/xgboost/
Error installing the following packages:
['xgboost==0.6a2']
Please install them manually
```

Now, given that xgboost is installed and works, I suppose two issues can cause the error : 
1. The version of xgboost is too old. We're running 0.6.
2. MLbox can't find the available xgboost version

Indeed, it MLbox seems to try and install xgboost 0.6a2 even though a version is already installed, which is surprising.

Maybe it is me.
Thank you for your help.

**Comment by brcacrm** [comment]
Detailed cmd print

> python setup.py install

> running install
> Requirement already satisfied: numpy==1.13.0 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: matplotlib==2.0.2 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: python-dateutil in /home/myname/anaconda3/lib/python3.6/site-packages (from matplotlib==2.0.2)
> Requirement already satisfied: pytz in /home/myname/anaconda3/lib/python3.6/site-packages (from matplotlib==2.0.2)
> Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /home/myname/anaconda3/lib/python3.6/site-packages (from matplotlib==2.0.2)
> Requirement already satisfied: cycler>=0.10 in /home/myname/anaconda3/lib/python3.6/site-packages (from matplotlib==2.0.2)
> Requirement already satisfied: numpy>=1.7.1 in /home/myname/anaconda3/lib/python3.6/site-packages (from matplotlib==2.0.2)
> Requirement already satisfied: six>=1.10 in /home/myname/anaconda3/lib/python3.6/site-packages (from matplotlib==2.0.2)
> Requirement already satisfied: hyperopt==0.1 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: pymongo in /home/myname/anaconda3/lib/python3.6/site-packages (from hyperopt==0.1)
> Requirement already satisfied: numpy in /home/myname/anaconda3/lib/python3.6/site-packages (from hyperopt==0.1)
> Requirement already satisfied: future in /home/myname/anaconda3/lib/python3.6/site-packages (from hyperopt==0.1)
> Requirement already satisfied: scipy in /home/myname/anaconda3/lib/python3.6/site-packages (from hyperopt==0.1)
> Requirement already satisfied: networkx in /home/myname/anaconda3/lib/python3.6/site-packages (from hyperopt==0.1)
> Requirement already satisfied: six in /home/myname/anaconda3/lib/python3.6/site-packages (from hyperopt==0.1)
> Requirement already satisfied: nose in /home/myname/anaconda3/lib/python3.6/site-packages (from hyperopt==0.1)
> Requirement already satisfied: decorator>=3.4.0 in /home/myname/anaconda3/lib/python3.6/site-packages (from networkx->hyperopt==0.1)
> Requirement already satisfied: Keras==2.0.4 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: pyyaml in /home/myname/anaconda3/lib/python3.6/site-packages (from Keras==2.0.4)
> Requirement already satisfied: theano in /home/myname/anaconda3/lib/python3.6/site-packages (from Keras==2.0.4)
> Requirement already satisfied: six in /home/myname/anaconda3/lib/python3.6/site-packages (from Keras==2.0.4)
> Requirement already satisfied: numpy>=1.9.1 in /home/myname/anaconda3/lib/python3.6/site-packages (from theano->Keras==2.0.4)
> Requirement already satisfied: scipy>=0.14 in /home/myname/anaconda3/lib/python3.6/site-packages (from theano->Keras==2.0.4)
> Requirement already satisfied: pandas==0.20.3 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: python-dateutil>=2 in /home/myname/anaconda3/lib/python3.6/site-packages (from pandas==0.20.3)
> Requirement already satisfied: pytz>=2011k in /home/myname/anaconda3/lib/python3.6/site-packages (from pandas==0.20.3)
> Requirement already satisfied: numpy>=1.7.0 in /home/myname/anaconda3/lib/python3.6/site-packages (from pandas==0.20.3)
> Requirement already satisfied: six>=1.5 in /home/myname/anaconda3/lib/python3.6/site-packages (from python-dateutil>=2->pandas==0.20.3)
> Requirement already satisfied: joblib==0.11 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: scikit-learn==0.19.0 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: Theano==0.9.0 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: numpy>=1.9.1 in /home/myname/anaconda3/lib/python3.6/site-packages (from Theano==0.9.0)
> Requirement already satisfied: scipy>=0.14 in /home/myname/anaconda3/lib/python3.6/site-packages (from Theano==0.9.0)
> Requirement already satisfied: six>=1.9.0 in /home/myname/anaconda3/lib/python3.6/site-packages (from Theano==0.9.0)
> Collecting xgboost==0.6a2
> Using cached xgboost-0.6a2.tar.gz
> Complete output from command python setup.py egg_info:
>   rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/metric.o src/metric/metric.cc >build/metric/metric.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/common/common.cc -o build/common/common.o
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/metric.cc -o build/metric/metric.o
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/logging.cc -o build/logging.o
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/learner.cc -o build/learner.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/rank_metric.o src/metric/rank_metric.cc >build/metric/rank_metric.d
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/elementwise_metric.o src/metric/elementwise_metric.cc >build/metric/elementwise_metric.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/rank_metric.cc -o build/metric/rank_metric.o
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/elementwise_metric.cc -o build/metric/elementwise_metric.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/multiclass_metric.o src/metric/multiclass_metric.cc >build/metric/multiclass_metric.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/multiclass_metric.cc -o build/metric/multiclass_metric.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/multiclass_obj.o src/objective/multiclass_obj.cc >build/objective/multiclass_obj.d
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/objective.o src/objective/objective.cc >build/objective/objective.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/multiclass_obj.cc -o build/objective/multiclass_obj.o
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/objective.cc -o build/objective/objective.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/rank_obj.o src/objective/rank_obj.cc >build/objective/rank_obj.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/rank_obj.cc -o build/objective/rank_obj.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/regression_obj.o src/objective/regression_obj.cc >build/objective/regression_obj.d
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_dmatrix.o src/data/sparse_page_dmatrix.cc >build/data/sparse_page_dmatrix.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/regression_obj.cc -o build/objective/regression_obj.o
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_dmatrix.cc -o build/data/sparse_page_dmatrix.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_source.o src/data/sparse_page_source.cc >build/data/sparse_page_source.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_source.cc -o build/data/sparse_page_source.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_writer.o src/data/sparse_page_writer.cc >build/data/sparse_page_writer.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_writer.cc -o build/data/sparse_page_writer.o
> g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/simple_csr_source.o src/data/simple_csr_source.cc >build/data/simple_csr_source.d
> g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/simple_csr_source.cc -o build/data/simple_csr_source.o
> In file included from src/data/sparse_page_writer.cc:8:0:
>   src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
> std::function<SparsePage::Format* ()> > {
>   ^~~~~~~~
>     src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
>   std::function<SparsePage::Format* ()> > {
>     ^~~~~~~~
>       is_function
>     src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
>     src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
>     std::function<SparsePage::Format* ()> > {
>       ^~~~~~~~
>         is_function
>       src/data/./sparse_batch_page.h:238:77: error: template argument 2 is invalid
>       std::function<SparsePage::Format* ()> > {
>         ^
>           src/data/./sparse_batch_page.h:238:79: error: expected ‘{’ before ‘>’ token
>             std::function<SparsePage::Format* ()> > {
>               ^
>                 src/data/./sparse_batch_page.h:238:79: error: expected unqualified-id before ‘>’ token
>               g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
>               g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/data.cc -o build/data/data.o
>               Makefile:105 : la recette pour la cible « build/data/sparse_page_writer.o » a échouée
>               make: *** [build/data/sparse_page_writer.o] Erreur 1
>               make: *** Attente des tâches non terminées....
>               In file included from src/data/data.cc:9:0:
>                 src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
>               std::function<SparsePage::Format* ()> > {
>                 ^~~~~~~~
>                   src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
>                 std::function<SparsePage::Format* ()> > {
>                   ^~~~~~~~
>                     is_function
>                   src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
>                   src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
>                   std::function<SparsePage::Format* ()> > {
>                     ^~~~~~~~
>                       is_function
>                     src/data/./sparse_batch_page.h:238:77: error: template argument 2 is invalid
>                     std::function<SparsePage::Format* ()> > {
>                       ^
>                         src/data/./sparse_batch_page.h:238:79: error: expected ‘{’ before ‘>’ token
>                           std::function<SparsePage::Format* ()> > {
>                             ^
>                               src/data/./sparse_batch_page.h:238:79: error: expected unqualified-id before ‘>’ token
>                             src/data/data.cc: In static member function ‘static xgboost::data::SparsePage::Format* xgboost::data::SparsePage::Format::Create(const string&)’:
>                               src/data/data.cc:283:12: error: invalid use of incomplete type ‘const struct xgboost::data::SparsePageFormatReg’
>                             return (e->body)();
>                             ^~
>                               In file included from src/data/data.cc:9:0:
>                               src/data/./sparse_batch_page.h:236:8: note: forward declaration of ‘struct xgboost::data::SparsePageFormatReg’
>                             struct SparsePageFormatReg
>                             ^~~~~~~~~~~~~~~~~~~
>                               src/data/data.cc:283:14: error: invalid use of incomplete type ‘const struct xgboost::data::SparsePageFormatReg’
>                             return (e->body)();
>                             ^~~~
>                               In file included from src/data/data.cc:9:0:
>                               src/data/./sparse_batch_page.h:236:8: note: forward declaration of ‘struct xgboost::data::SparsePageFormatReg’
>                             struct SparsePageFormatReg
>                             ^~~~~~~~~~~~~~~~~~~
>                               In file included from dmlc-core/include/dmlc/data.h:16:0,
>                             from include/xgboost/data.h:11,
>                             from src/data/data.cc:5:
>                               dmlc-core/include/dmlc/./registry.h: In instantiation of ‘dmlc::Registry<EntryType>::~Registry() [with EntryType = xgboost::data::SparsePageFormatReg]’:
>                               src/data/data.cc:21:1:   required from here
>                             dmlc-core/include/dmlc/./registry.h:91:7: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
>                             delete p->second;
>                             ^~~~~~
>                               dmlc-core/include/dmlc/./registry.h:91:17: warning: invalid use of incomplete type ‘struct xgboost::data::SparsePageFormatReg’
>                             delete p->second;
>                             ~~~^~~~~~
>                               In file included from src/data/data.cc:9:0:
>                               src/data/./sparse_batch_page.h:236:8: note: forward declaration of ‘struct xgboost::data::SparsePageFormatReg’
>                             struct SparsePageFormatReg
>                             ^~~~~~~~~~~~~~~~~~~
>                               In file included from dmlc-core/include/dmlc/data.h:16:0,
>                             from include/xgboost/data.h:11,
>                             from src/data/data.cc:5:
>                               dmlc-core/include/dmlc/./registry.h:91:7: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
>                             delete p->second;
>                             ^~~~~~
>                               Makefile:105 : la recette pour la cible « build/data/data.o » a échouée
>                             make: *** [build/data/data.o] Erreur 1
>                             -----------------------------
>                               Building multi-thread xgboost failed
>                             Start to build single-thread xgboost
>                             rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/metric.o src/metric/metric.cc >build/metric/metric.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/logging.cc -o build/logging.o
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/metric.cc -o build/metric/metric.o
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/common/common.cc -o build/common/common.o
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/learner.cc -o build/learner.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/rank_metric.o src/metric/rank_metric.cc >build/metric/rank_metric.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/rank_metric.cc -o build/metric/rank_metric.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/elementwise_metric.o src/metric/elementwise_metric.cc >build/metric/elementwise_metric.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/elementwise_metric.cc -o build/metric/elementwise_metric.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/metric/multiclass_metric.o src/metric/multiclass_metric.cc >build/metric/multiclass_metric.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/metric/multiclass_metric.cc -o build/metric/multiclass_metric.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/multiclass_obj.o src/objective/multiclass_obj.cc >build/objective/multiclass_obj.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/multiclass_obj.cc -o build/objective/multiclass_obj.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/objective.o src/objective/objective.cc >build/objective/objective.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/objective.cc -o build/objective/objective.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/rank_obj.o src/objective/rank_obj.cc >build/objective/rank_obj.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/rank_obj.cc -o build/objective/rank_obj.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/objective/regression_obj.o src/objective/regression_obj.cc >build/objective/regression_obj.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/objective/regression_obj.cc -o build/objective/regression_obj.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_dmatrix.o src/data/sparse_page_dmatrix.cc >build/data/sparse_page_dmatrix.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_dmatrix.cc -o build/data/sparse_page_dmatrix.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_source.o src/data/sparse_page_source.cc >build/data/sparse_page_source.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_source.cc -o build/data/sparse_page_source.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/sparse_page_writer.o src/data/sparse_page_writer.cc >build/data/sparse_page_writer.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/sparse_page_writer.cc -o build/data/sparse_page_writer.o
>                             g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/simple_csr_source.o src/data/simple_csr_source.cc >build/data/simple_csr_source.d
>                             g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/simple_csr_source.cc -o build/data/simple_csr_source.o
>                             In file included from src/data/sparse_page_writer.cc:8:0:
>                               src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
>                             std::function<SparsePage::Format* ()> > {
>                               ^~~~~~~~
>                                 src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
>                               std::function<SparsePage::Format* ()> > {
>                                 ^~~~~~~~
>                                   is_function
>                                 src/data/./sparse_batch_page.h:238:46: error: ‘function’ is not a member of ‘std’
>                                 src/data/./sparse_batch_page.h:238:46: note: suggested alternative: ‘is_function’
>                                 std::function<SparsePage::Format* ()> > {
>                                   ^~~~~~~~
>                                     is_function
>                                   src/data/./sparse_batch_page.h:238:77: error: template argument 2 is invalid
>                                   std::function<SparsePage::Format* ()> > {
>                                     ^
>                                       src/data/./sparse_batch_page.h:238:79: error: expected ‘{’ before ‘>’ token
>                                         std::function<SparsePage::Format* ()> > {
>                                           ^
>                                             src/data/./sparse_batch_page.h:238:79: error: expected unqualified-id before ‘>’ token
>                                           Makefile:105 : la recette pour la cible « build/data/sparse_page_writer.o » a échouée
>                                           make: *** [build/data/sparse_page_writer.o] Erreur 1
>                                           make: *** Attente des tâches non terminées....
>                                           Successfully build single-thread xgboost
>                                           If you want multi-threaded version
>                                           See additional instructions in doc/build.md
>                                           Traceback (most recent call last):
>                                             File "<string>", line 1, in <module>
>                                             File "/tmp/pip-build-gakby3y8/xgboost/setup.py", line 29, in <module>
>                                             LIB_PATH = libpath['find_lib_path']()
>                                           File "/tmp/pip-build-gakby3y8/xgboost/xgboost/libpath.py", line 45, in find_lib_path
>                                           'List of candidates:\n' + ('\n'.join(dll_path)))
> XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
>   List of candidates:
>   /tmp/pip-build-gakby3y8/xgboost/xgboost/libxgboost.so
> /tmp/pip-build-gakby3y8/xgboost/xgboost/../../lib/libxgboost.so
> /tmp/pip-build-gakby3y8/xgboost/xgboost/./lib/libxgboost.so
> 
> ----------------------------------------
>   Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gakby3y8/xgboost/
>   Requirement already satisfied: lightgbm==2.0.2 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: scikit-learn in /home/myname/anaconda3/lib/python3.6/site-packages (from lightgbm==2.0.2)
> Requirement already satisfied: numpy in /home/myname/anaconda3/lib/python3.6/site-packages (from lightgbm==2.0.2)
> Requirement already satisfied: wheel in /home/myname/anaconda3/lib/python3.6/site-packages (from lightgbm==2.0.2)
> Requirement already satisfied: scipy in /home/myname/anaconda3/lib/python3.6/site-packages (from lightgbm==2.0.2)
> Requirement already satisfied: networkx==1.11 in /home/myname/anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: decorator>=3.4.0 in /home/myname/anaconda3/lib/python3.6/site-packages (from networkx==1.11)
> 
> Error installing the following packages:
>   ['xgboost==0.6a2']
> Please install them manually
> 
> error: Aborting

**Comment by AxeldeRomblay** [comment]
Hello ! 
What is your OS please ? MLBox setup is for Ubuntu only... Otherwise you will need to install xgboost 0.6a2 and lightgbm 2.0.2. manually... (see requirements.txt file)
Please tell me if you still get some trouble for the setup.
Thanks !

**Comment by brcacrm** [comment]
Hi,

My OS is Ubuntu 17.10.
I already tried with xgboost 0.6a2 and lightgbm 2.02 installed manually and get the same error.

Maybe it's me.
Thank you for your help.

**Comment by AxeldeRomblay** [comment]
You also need to install gcc and cmake...

**Comment by brcacrm** [comment]
cmake 0.9.0 and  gcc 7.2.0 are installed

**Comment by AxeldeRomblay** [comment]
Anyway for the next release, xgboost will be an optional requirement for the setup...

**Comment by chetankalyan** [comment]
@AxeldeRomblay  - I'm facing the same issue on my Ubuntu 17.10 machine.
gcc - 7.2.0
cmake - 3.9.1
When I try `pip install xgboost`, it says xgboost 0.7-py3.6 is already installed. Is there a way I can make MLBox work with xgboost 0.7?

**Comment by manugarri** [comment]
@AxeldeRomblay Is there an expected date for the next release? I see that the last one was in August 2017, I am experiencing this same problem (conda environment in Ubuntu 18.04 with xgboost working) and would love to give mlbox a try.

**Comment by istrategy** [comment]
I also get the error.
Ubuntu Linux 18.05
Python version 3.5 
Anaconda 3 environment.

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-k_n8jdl_/xgboost/

**Comment by Henri-Gerard** [comment]
I set up a virtual environment on Ubuntu 18.10 and I got the following error : 
_setuptools.sandbox.UnpickleableException: XGBoostLibraryNotFound('Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?_

Then I quit virtual environment, install xgboost manually and globally and I end up with the same error. 

Then I adapt as suggested by @liuzhenhai93 the file setup.py replacing
`"xgboost==0.6a2"`
by
`"xgboost>=0.6a2"`
and it works. 

I think modifying the setup.py file would be a good option

**Comment by AxeldeRomblay** [comment]
Sorry for the late answer... We are working on replacing xgboost by lightgbm for the next release as both models are almost equivalent ;)

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since this is now fixed.
