### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by easonlv** [AxeldeRomblay/MLBox#56]
Collecting xgboost==0.6a2
  Downloading xgboost-0.6a2.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 358kB/s 
    Complete output from command python setup.py egg_info:
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    /bin/sh: clang-omp++: command not found
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    make: *** [build/learner.o] Error 127
    make: *** Waiting for unfinished jobs....
    /bin/sh: clang-omp++: command not found
    make: *** [build/logging.o] Error 127
    -----------------------------
    Building multi-thread xgboost failed
    Start to build single-thread xgboost
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/learner.o] Error 127
    make: *** Waiting for unfinished jobs....
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/logging.o] Error 127
    Successfully build single-thread xgboost
    If you want multi-threaded version
    See additional instructions in doc/build.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sr/dbsldvwn0fg1p3wp248kjz0w0000gn/T/pip-build-LkVyg6/xgboost/setup.py", line 29, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/sr/dbsldvwn0fg1p3wp248kjz0w0000gn/T/pip-build-LkVyg6/xgboost/xgboost/libpath.py", line 45, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    __builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/sr/dbsldvwn0fg1p3wp248kjz0w0000gn/T/pip-build-LkVyg6/xgboost/xgboost/libxgboost.so
    /private/var/folders/sr/dbsldvwn0fg1p3wp248kjz0w0000gn/T/pip-build-LkVyg6/xgboost/xgboost/../../lib/libxgboost.so
    /private/var/folders/sr/dbsldvwn0fg1p3wp248kjz0w0000gn/T/pip-build-LkVyg6/xgboost/xgboost/./lib/libxgboost.so
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sr/dbsldvwn0fg1p3wp248kjz0w0000gn/T/pip-build-LkVyg6/xgboost/

----

Error installing the following packages:
['xgboost==0.6a2']
Please install them manually

error: Aborting

Please help solving this problem, thanks

**Comment by AxeldeRomblay** [comment]
Hello !
What is your OS please ? MLBox setup is for Ubuntu only... Otherwise you will need to install xgboost 0.6a2 and lightgbm 2.0.2. manually... (see requirements.txt file)

Also you will need to install gcc and cmake first (see readme.rst)

Please tell me if you still get some trouble for the setup.
Thanks !

**Comment by easonlv** [comment]
Thanks very much.
My computer OS is Mac OS 10.13.2,
I use xgboost and lightgbm for a long time.
I installed xgboost(0.6) and lightgbm (2.0.10)
I installed gcc like this .
----------------------
>gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.41)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by amitsri20** [comment]
I am trying to install MLBox on macOS high Sierra but getting 
`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vj/00_03krx25d8tmkxx_9cxpl5f40180/T/pip-install-jtf94l52/xgboost/`

I have already installed xgboost, lightgbm, gcc and cmake.

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since this is now fixed...
