### ISSUE TITLE
Pinned version of dependencies

### ISSUE THREAD

**Issue by rth** [AxeldeRomblay/MLBox#58]
MLbox currently uses pinned versions of dependencies,
https://github.com/AxeldeRomblay/MLBox/blob/35e0be57b25fa64b1ac8561094f58aaf62527d41/python-package/setup.py#L8-L20

which doesn't play very nicely with other possibly installed packages in the environment. Relaxing at least some of these would be helpful.

**Comment by AxeldeRomblay** [comment]
Thanks @rth ! Indeed it will be done for the next release :)

**Comment by sugiantolauw** [comment]
Hi @AxeldeRomblay , when would the next release be? I would like to play around with this package but i am on xgboost=0.7 unfortunately.

**Comment by AxeldeRomblay** [comment]
I just need one month more...

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since this is now fixed...
