### ISSUE TITLE
Target encoding

### ISSUE THREAD

**Issue by mileta1976** [AxeldeRomblay/MLBox#59]
Hello.

Great package Axel !

Could you add target encoding ?

https://www.kaggle.com/ogrellier/python-target-encoding-for-categorical-features

Thank you !

**Comment by AxeldeRomblay** [comment]
Hello ! Thanks. I was already working on it... :) it will be soon released don't worry !

**Comment by AxeldeRomblay** [comment]
here is the code to do it : https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/target_encoder.py

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since this feature will be added in a next release (MLBox 1.0.0 probably)
