### ISSUE TITLE
Comparison of AutoML approaches

### ISSUE THREAD

**Issue by ShagadatovNurlan** [AxeldeRomblay/MLBox#62]
Hello, we are analyzing AutoML libraries(such as Auto-sklearn, Auto-ml, TPOT and MLBox) and try to determine pros and cons of each of them. Could you clarify the distinctive feature of your MLBox from others? In particular, we are interesting in problem of regression (time series with additional features)

**Comment by AxeldeRomblay** [comment]
Hello, everything is here : https://github.com/AxeldeRomblay/MLBox/blob/master/docs/webinars/auto-ML.pdf :)

**Comment by abhiglobalistic** [comment]
Hey @ShagadatovNurlan,
Is it possible for you to briefly describe your approach on how you are trying to compare the libraries. like the metrics used, datasets and what sort of criteria have you designed to compare them ?

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since the doc is available here : https://github.com/AxeldeRomblay/MLBox/tree/master/docs/webinars and https://mlbox.readthedocs.io/en/latest/#links.
