### ISSUE TITLE
You have no test dataset ! 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [AxeldeRomblay/MLBox#64]
**I already split my dataset into X_train and X_test**
___

why this issue occurs ? please help

![image](https://user-images.githubusercontent.com/42869040/57008285-995e1d00-6c0c-11e9-9499-f675a9af7225.png)

**Comment by AxeldeRomblay** [comment]
Hi ! Normally the test set does not contain the target... if you still want to predict on this set you have to remove the target... Otherwise it will concatenate both set and evaluate the model in a cross-validation way.

**Comment by VinayChaudhari1996** [comment]
Thanks, man It works :)

![image](https://user-images.githubusercontent.com/42869040/57065364-cda60c00-6ce6-11e9-944e-3d5439aed850.png)
