### ISSUE TITLE
How to save model in .pkl or joblib ?

### ISSUE THREAD

**Issue by VinayChaudhari1996** [AxeldeRomblay/MLBox#66]
I have RUN mlbox in one system and which automatically generate SAVE folder is directory so ,I copy this SAVE folder in another pc and try to run below command. and got error>
**My biggest issue is** , 
___

### HOW I SERVE MY MODEL LIKE .PKL IN OTHER PC AND PREDICT SINGLE RECORD

![image](https://user-images.githubusercontent.com/42869040/57288626-75e91580-70d7-11e9-95af-7719b5e22a03.png)

**Comment by AxeldeRomblay** [comment]
Hello ! Thank you for the issue ! We will add this feature for the next release :)

**Comment by VinayChaudhari1996** [comment]
1) joblib & pickle - save model and load model

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since this feature will be added in a next release (MLBox 1.0.0 probably)
