### ISSUE TITLE
Trying to install mlbox on ubuntu 18.05 but getting errors

### ISSUE THREAD

**Issue by yckoong** [AxeldeRomblay/MLBox#67]
Hi, Thanks for creating such an awesome package, i have got lot of good review on 'mlbox' and i always want to try it :)  

I'm trying to install mlbox on `Ubuntu 18.04.2 LTS` & `Python 3.7.3` , but getting some errors while installation.

I have done install per-requisite (refer to [Installation guide](https://github.com/AxeldeRomblay/MLBox/tree/master/python-package)) before install `mlbox`, below are the details:~
 1) gcc - **Done**
`build-essential:
  Installed: 12.4ubuntu1
  Candidate: 12.4ubuntu1
  Version table:
 *** 12.4ubuntu1 500
        500 http://mirror.pregi.net/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
`

2) cmake - **Done**
`cmake:
  Installed: (none)
  Candidate: 3.10.2-1ubuntu2
  Version table:
     3.10.2-1ubuntu2 500
        500 http://mirror.pregi.net/ubuntu bionic/main amd64 Packages`

3) xgboost - **Done**
`Name: xgboost
Version: 0.82
Summary: XGBoost Python Package
Home-page: https://github.com/dmlc/xgboost
Author: Hyunsu Cho
Author-email: chohyu01@cs.washington.edu
License: Apache-2.0
Location: /home/lenovo/anaconda/anaconda3/lib/python3.7/site-packages
Requires: scipy, numpy
Required-by: auto-sklearn
`
4) lightGBM - **Done**
`Name: lightgbm
Version: 2.2.3
Summary: LightGBM Python Package
Home-page: https://github.com/Microsoft/LightGBM
Author: None
Author-email: None
License: The MIT License (Microsoft)
Location: /home/lenovo/anaconda/anaconda3/lib/python3.7/site-packages
Requires: scipy, scikit-learn, numpy
Required-by:`

After install all pre-requisite above, i proceed to `pip install mlbox` but getting errors (attached is the [mlbox installation log file](https://github.com/yckoong/share_folder/blob/master/install%20log.txt))

Could you assist? Thanks!

**Comment by yckoong** [comment]
Solved the issue by downgrade numpy to `numpy==1.13.3` & downgrade python version from `3.7.3` to `3.6.8` since MLbox is compatible with: **Python 2.7 - 3.6. & 64-bit version only**

**Comment by AxeldeRomblay** [comment]
Great you found the solution :) thanks !
