### ISSUE TITLE
Regarding Text classification

### ISSUE THREAD

**Issue by Joselinejamy** [AxeldeRomblay/MLBox#68]
Hello, 
Am getting poor results on classifying texts. Is this expected or should i change any search space ?. 

P.S  Am using default search space

**Comment by AxeldeRomblay** [comment]
Hello ! It is normal for the moment but the next release will handle text classification :) you can have a look at the dev branch...

**Comment by AxeldeRomblay** [comment]
Hello, thanks for reporting this issue. I will close it since text classification option will be added in a next release (MLBox 1.0.0 probably)
