### ISSUE TITLE
Setup script exited with usage: setup.py [global_opts] error: no commands supplied

### ISSUE THREAD

**Issue by NeerajSarwan** [AxeldeRomblay/MLBox#7]
Hi AxeldeRomblay,

System Information
Ubuntu 16.04

I was actually trying to install your MLBox to give it a try. The steps I took were -
1- clone the repository.
2- run setup.py file.

The building part finishes till 100% but then throws a couple of errors. I am posting the actual error below.

[100%] Linking CXX shared library /tmp/easy_install-1gz4zwpu/lightgbm-2.0.2/lightgbm/lib_lightgbm.so
[100%] Built target _lightgbm
Install lib_lightgbm from: ['lightgbm/lib_lightgbm.so']
error: Setup script exited with usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied.

**Comment by AxeldeRomblay** [comment]
Hello ! 
Yes it seems there is a problem while installing lightgbm from PyPI. 
- either you install it on your own (https://github.com/Microsoft/LightGBM/tree/master/python-package)
- or (simpler) : install mlbox from the wheel : 

  $ cd python-package/dist/
  $ pip install *.whl  

I think it should work...

**Comment by NCherel** [comment]
Try ```python setup.py install```

**Comment by NeerajSarwan** [comment]
@AxeldeRomblay 
I ran your commands and it said - mlbox-0.2.2-py2-none-any.wheel is not a supported wheel on this platform.

**Comment by NeerajSarwan** [comment]
@NCherel 
 
I already tried running python setup.py install but it throws the error mentioned in the original issue.

**Comment by AxeldeRomblay** [comment]
At the moment mlbox only works for python 2. but we are working on this point to make it compatible with python 3. :)

**Comment by brunosez** [comment]
I have the same issue with conda virtualenv , ubuntu 14.04.
it worked correctly with whell install...

**Comment by arunkumar3234** [comment]
@NeerajSarwan 
 I have the same issue help me overcome with this 
Thanks

**Comment by vazhameladze** [comment]
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]               or: setup.py --help [cmd1 cmd2 ...]                                              or: setup.py --help-comma
--

**Comment by Henri-Gerard** [comment]
You should use either
python setup.py install 
if you just want to use the package
or 
python setup.py develop
if you want to contribute. 

This error comes often when one forgot to provide "install" or "develop" argument

**Comment by CrystaljhSun** [comment]
> You should use either
> python setup.py install
> if you just want to use the package
> or
> python setup.py develop
> if you want to contribute.
> 
> This error comes often when one forgot to provide "install" or "develop" argument

Really, when I add the command 'install' it seems to work now. Thank you!

**Comment by Kulsumganihar** [comment]
Tried with all the solutions provided here, still getting same error.
After using python setup.py install all the required packages are getting installed. But when I try to run the file I am getting following error.
`usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied`

**Comment by ihusky02** [comment]
Hi,

I try install youtube-dl-gui for Zorin 15 and python setup.py install command worked, but I don`t see this app?

https://pastebin.com/wLBvUW3U

**Comment by kazimsayed954** [comment]
python setup.py install

or

python setup.py build

or

python setup.py build_exe

**Comment by messiasab** [comment]
python setup.py build_exe

**Comment by messiasab** [comment]
ValueError: Cannot find required utility `patchelf` in PATH

**Comment by mbrsagor** [comment]
`python setup.py bdist_wheel`

**The code does not work. below is the error message:**

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by Ibrah-N** [comment]
Facing the same issue
