### ISSUE TITLE
module mlbox.preprocessing not found error when my mlbox.py in the same folder

### ISSUE THREAD

**Issue by Nithanaroy** [AxeldeRomblay/MLBox#76]
When I have `mlbox.py` file in the same folder, 

```python
from mlbox.preprocessing import *
from mlbox.optimisation import *
from mlbox.prediction import *
```
throws an error saying `module mlbox.preprocessing not found`. On changing the filename of that python file to something else, it works fine. However, it was a little confusion why the above lines were executing the code from my `mlbox.py` file.

**Comment by AxeldeRomblay** [comment]
Hello @Nithanaroy, when you run the import command in python you can both import from a package or from a script. That's why here it is confusing because you don't have a preprocessing function in your script mlbox.py...
