### ISSUE TITLE
Comparison to similar packages

### ISSUE THREAD

**Issue by ogencoglu** [AxeldeRomblay/MLBox#80]
Thank you a lot for the great effort!

What are the advantages and disadvantages compared to similar packages especially in hyper-parameter optimization? :

- https://github.com/minimaxir/automl-gs

- https://github.com/HunterMcGushion/hyperparameter_hunter

- https://github.com/pfnet/optuna/

- https://github.com/EpistasisLab/tpot

- https://github.com/keras-team/autokeras

- https://github.com/hyperopt/hyperopt-sklearn

- https://github.com/claesenm/optunity

- https://github.com/maxpumperla/hyperas

- https://github.com/HIPS/Spearmint

**Comment by AxeldeRomblay** [comment]
Hello @ogencoglu ! Glad to see you like the package :) 

Actually I would say that MLBox is the only python open source package that automates **all the steps** (reading, splitting train/test, preprocessing, feature encoding, robust feature selection, hyper-parameters tuning, model interpretation and prediction, stacking...). 

You can find more details here : 
- https://github.com/AxeldeRomblay/MLBox/blob/master/docs/webinars/auto-ML.pdf
- https://github.com/AxeldeRomblay/MLBox/blob/master/docs/webinars/features.pdf

Regarding hyper-parameter optimization, MLBox is built on the top of hyperopt, so it is equivalent. 
You can optimize all the parameters (missing values imputing, feature encoding, model selection and parameters...) 

If something is not clear, please let me know !

**Comment by ogencoglu** [comment]
Thanks for the swift reply! Cheers!
