### ISSUE TITLE
How to force classification ?

### ISSUE THREAD

**Issue by brunosez** [AxeldeRomblay/MLBox#87]
Hi,
On this simple dataset, target type is detected as float, I try to force to int in pre-preprocessing
but no way ?
Do you have an idea ?
Thanks
Bruno

https://www.kaggle.com/c/learn-together/data

train[['Cover_Type']] = train[['Cover_Type']].astype(int)
train.to_csv("../input/train2.csv",index=False)

**Comment by AxeldeRomblay** [comment]
Hello @brunosez, 
Could you please re-send me the link ? it does not work... 
Thanks !

**Comment by brunosez** [comment]
Hello Axel
Here : https://www.kaggle.com/c/learn-together
Have a nice day !

**Comment by brunosez** [comment]
In fact, same issue as 2y ago
task = "regression"
            count = y_train.nunique()

            if (count <= 2):
                task = "classification"

            else:
                if (y_train.dtype == object):
                    task = "classification"
I will force target column to be an object...
Rgds

**Comment by AxeldeRomblay** [comment]
Indeed, if your target looks like this : y = ["2", "1", "10", ... ,"5"], it will be considered as a regression problem (which is often relevant...) . Otherwise, try to cast it like this : y = ["C2", "C1", "C10", ... ,"C5"].
