### ISSUE TITLE
 how to set KERAS_BACKEND ?

### ISSUE THREAD

**Issue by brunosez** [AxeldeRomblay/MLBox#9]
I have warning / errors with Theano backend.
So I want to switch to tensorflow.
I have a conda virtualenv , in general I set the keras.json file but here ?

Trying
os.environ["KERAS_BACKEND"] = "tensorflow"
from mlbox.preprocessing import *
from mlbox.optimisation import *
from mlbox.prediction import *
seems not worked

Thanks
Bruno

**Comment by NCherel** [comment]
Yes, you need to change that line.
Don't forget to reinstall the package after so your changes are effective.

**Comment by brunosez** [comment]
Thanks,
changing the line, force Tf Backend
unfortunately I get stuck with some tf installation

**Comment by AxeldeRomblay** [comment]
@brunosez : Actually, it seems that tensorflow installation is a bit more complicated than theano. So we decided not to install tf but theano and to force theano backend when importing the module "encoding" (file categorical_encoder.py).

**Comment by brunosez** [comment]
OK, you're right TF install with the correct GPU settings could be touchy !
