### ISSUE TITLE
MLbox  predict issue

### ISSUE THREAD

**Issue by sathvikchiramana** [AxeldeRomblay/MLBox#92]
when i  run fit_predict function its continuously running and not outputting any csv file ,it got stuck in the middle,i try to run it from jupyternotebook as well as idle,my os is windows 10
![Screenshot (6)](https://user-images.githubusercontent.com/57037932/73816448-adbfed80-480e-11ea-88a7-53016e346239.png)
![Screenshot (7)](https://user-images.githubusercontent.com/57037932/73816451-aef11a80-480e-11ea-9f15-5f6174dd7dcb.png)

**Comment by AxeldeRomblay** [comment]
Hello @sathvikchiramana ! What is the size of your data set ? Also I think you should have a window with the features importance that has popped up after fitting the pipeline and you need to close it... is it the case ?

**Comment by sathvikchiramana** [comment]
Yes I corrected it myself,it worked

**Comment by AxeldeRomblay** [comment]
ok i close the issue then !
