### ISSUE TITLE
Why does mlbox recognize my multi-class training set as a regression problem

### ISSUE THREAD

**Issue by gaoexingyun** [AxeldeRomblay/MLBox#94]
I originally wanted to train my multi-class training set with mlbox classification, but after importing the data, it automatically recognized it as regression, and changed my target value data type from int to float.

**Comment by AxeldeRomblay** [comment]
Hello @gaoexingyun, 
Thanks for the issue ! You can refer to this one : https://github.com/AxeldeRomblay/MLBox/issues/87

To sum it up, MLBox always tries to cast your target into float so if you have something like : "1", "2", ... it is considered as a regression problem, better if your target looks like "C1", "C2", ... 

Please tell me if it works now.

**Comment by gaoexingyun** [comment]
> Hello @gaoexingyun,
> Thanks for the issue ! You can refer to this one : #87
> 
> To sum it up, MLBox always tries to cast your target into float so if you have something like : "1", "2", ... it is considered as a regression problem, better if your target looks like "C1", "C2", ...
> 
> Please tell me if it works now.

Thank you. It works.
