### ISSUE TITLE
Build Fails Using Pip, TF 1.14.0 Requirement Cannot Be Satisfied

### ISSUE THREAD

**Issue by Rubix982** [AxeldeRomblay/MLBox#97]
Hi! 

# OS / Package Version 

OS: `Linux archlinux 5.5.3-arch1-1 #1 SMP PREEMPT Tue, 11 Feb 2020 15:35:41 +0000 x86_64 GNU/Linux`
Python: `3.8.1`

# The Issue

The current build ( commit 0c99b2fc4292d4e2d33b197c1652574ed38bb21b ) fails for me when I try to install mlbox from pip using the below command,
`sudo pip install mlbox`

At the end, I received the following error
```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from mlbox) (from versions: 2.2.0rc1, 2.2.0rc2)
ERROR: No matching distribution found for tensorflow==1.14.0 (from mlbox)
```

I tried to manually install `tensorflow 1.14.0` using
```
sudo pip install tensorflow==1.14.0
```

But it turns out pip cannot find any version of Tensorflow for its 1.14.0.
It's an issue with Tf itself. Posting it here because,

1): We can, or should, update the version of Tf in the requirements itself. I would make a pull request but I'm afraid it might break other dependencies as well
2): Make an issue at Tf about the version problem itself ( I'll do that ).

# What Should I Happen

Install, basically.

**Comment by Rubix982** [comment]
Relevant issue at tensorflow/tensorflow can be found [here](https://github.com/tensorflow/tensorflow/issues/28785) .

**Comment by AxeldeRomblay** [comment]
Hello @Rubix982, thank you for reporting this issue. Actually, the PR already exists : https://github.com/AxeldeRomblay/MLBox/pull/91, but I will see if I can directly upgrade to tf 2.0... without breaking any dependencies ! ;) 

Also as I see that you are working on py 3.8, I will try to upgrade MLBox.

**Comment by Rubix982** [comment]
Okay, thank you so much.
I did not look into the PRs beforehand, my apologies.
